### ISSUE TITLE
Добавить создание объектов панелей

### ISSUE THREAD

**Issue by AK1Chel** [Anisan/majordomo-openhasp#3]
Практика показала, что для полноценной работы панели необходим объект, привязанный к этой панели.
Для полноты модуля я бы предложил при  установке модуля автоматически создавать объект панели с основными необходимыми свойствами. За основу взять объекты xor.   Свойства объекта: page  lwt ip idle brightness.  backlight . И еще добавить TAB (номер закладки на странице).

**Comment by xor2016** [comment]
TAB не нужен, его может и не быть в дизайне. uptime можно добавить, если там проблемы с поведением после перезагрузки. Достаточно строку добавить в разбор statusupdate
403 строкой `$this->setLinkedProperty($panel,"uptime", $value["uptime"]);`
обновление приходит после перезагрузки и с периодом 5 минут
можно обновить в произвольное время командой statusupdate
